### ISSUE TITLE
Issue importing icons

### ISSUE THREAD

**Issue by xoniq** [bigtreetech/BIGTREETECH-TFT35-V1.2#28]
Hello,

I'm running the TFT35, but tried to create custom icons. But my icon become distorted when being imported into the screen.

I'm using a Mac, so I dont have much options for BMP stuff. So I create it as a PNG, and use ImageMagick to convert it to BMP without alpha. The colors are fine, it tries to import, but the image is imported as show below.

How can I solve this?

![IMG_1390](https://tweakers.net/ext/f/ha4vZT7IFzi8oshJo09iOYzZ/full.jpg?nohitcount=1)

**Comment by bleughb** [comment]
Upgrade to the latest firmware

**Comment by xoniq** [comment]
Already using it. V1.2.11.
That's the version where I have this issue.

**Comment by Msq001** [comment]
Is the pixels of your icon is 95*95?

**Comment by dianlight** [comment]
Hi,
 di you found a solution? I'have the same problem on a Mac with ImageMagic.

**Comment by xoniq** [comment]
@Msq001:
Yes, exactly that size. Weird part is; the boot screen is correct, icons all distorted.

@dianlight:
No haven't been able to fix...

**Comment by Msq001** [comment]
@dianlight @xoniq  can you send me a icon that I can check it

**Comment by Msq001** [comment]
my e-mail: 3001154986@qq.com

**Comment by Msq001** [comment]
So sorry for that,  I've confirmed that this is a bug decoding BMP file in the bootloader,  I'm thinking about moving the code of decode BMP and bitmaps fonts from bootloader to app code. and fix this bug,   before this, you can avoid this bug by setting the bit depth of the icon to 32 bits instead of 24/16 bits. as shown in the following picture.
![image](https://user-images.githubusercontent.com/25599056/59000364-bc4ba480-883c-11e9-92e9-6d5a67c443fa.png)

**Comment by xoniq** [comment]
@Msq001,

Thanks, will try it at 32 bit tonight, if it doesn’t work I’ll send the BMP file in a zip file here in a reply (so it doesn’t get altered)

**Comment by dianlight** [comment]
It works for me! But in reality it is not enough to switch to 32bit it is also necessary to check that ImageMagick in the passage does not pass from bmp v3 to bmp v4.

This is the command I used to "fix" the Reserved_6.bpm

Before:
```
$ file Reserve_6.bmp
Reserve_6.bmp: PC bitmap, Windows 3.x format, 95 x 95 x 24
```

Transformation:
` $ convert Reserve_6.bmp -alpha set -define bmp:format=bmp3 -define bmp3:alpha=true Reserve_6.bmp`

After:
```
$ file Reserve_6.bmp
Reserve_6.bmp: PC bitmap, Windows 3.x format, 95 x 95 x 32
```

**Comment by xoniq** [comment]
@dianlight Thanks for the suggestion, i'm gonna try it in a few hours. Already tried one file.

**Before:**
```
Fast.bmp: PC bitmap, Windows 98/2000 and newer format, 95 x 95 x 32
```
**Command:**
```
convert Fast.bmp -alpha set -define bmp:format=bmp3 -define bmp3:alpha=true Fast.bmp
```
**After:**
```
Fast.bmp: PC bitmap, Windows 3.x format, 95 x 95 x 32
```
I will post my results here in a few hours.

**Comment by xoniq** [comment]
@dianlight @Msq001

The solution of @dianlight was the key (THANKS!). Now all images are perfectly imported.

This issue can be closed with this information for macOS and Linux users.
