### ISSUE TITLE
How to compile firmware?

### ISSUE THREAD

**Issue by ArturNadolski** [bigtreetech/BIGTREETECH-TFT35-V1.2#6]
How to compile firmware?
I would like to change some code but there is no information how to compile firmware.

**Comment by elandesign** [comment]
Same here. Anyone got any info?...

**Comment by Sthopeless** [comment]
any news on how to compile the firmware?

**Comment by Msq001** [comment]
hi.  we have updated the source code,  and add the "vscode + platformio" project,  you can download it and compile it by platformio
